### ISSUE TITLE
I don't have Numpad

### ISSUE THREAD

**Issue by SixKuse** [Kramar1337/WutheringWaves-AHK-flex#1]

**Comment by Kramar1337** [comment]
open with notepad and change the buttons
https://www.autohotkey.com/docs/v1/KeyList.htm

key_LabelNumpad0 := "Numpad0"
key_LabelNumpad1 := "Numpad1"
key_LabelNumpad2 := "Numpad2"
key_LabelNumpad3 := "Numpad3"
