### ISSUE TITLE
Improvements for Chixia script

### ISSUE THREAD

**Issue by XCanG** [Kramar1337/WutheringWaves-AHK-flex#2]
I've only checked script for Chixia part and had some issues with it, so I rewrite it a bit. A few points I want to bring here:

First x and y coords https://github.com/Kramar1337/WutheringWaves-AHK-flex/blob/main/WWFlex/WWFlex.ahk#L469
Even if it counted sort of relatively, it still not work in all cases. In my case I have 1920x1200 monitor and desired pixel within area:
![image](https://github.com/Kramar1337/WutheringWaves-AHK-flex/assets/4011523/30a2b156-c3e4-4126-a50c-3f5eae91f51a)
I choose x - 1323, y - 1101.
Also would be better to put it outside of loop.

I think it would be better to put in config.

As for the colors, they also don't really match even in center bold part. At first I collected this colors:
```ahk
if (GetPix = 0xFF0000 || GetPix = 0xFD0000 || GetPix = 0xFC0101 || GetPix = 0xFE0000 || GetPix = 0xAA1318 || GetPix = 0x8A1921 || GetPix = 0xCE0A07 || GetPix = 0x871B15) {
```
But then I completely abandoned this idea and rewrite it instead.
I save 2 variables for red and dark red colors and use approximation function:
```ahk
red := 0xFF0000
dark_red := 0x871B15
delta := 12

xPix := 1323
yPix := 1101


ColorRGBCompare(col1, col2, d) {
	col1 := RGBfromColor(col1)
	col2 := RGBfromColor(col2)
	return (Abs(col1.r - col2.r) <= d) && (Abs(col1.g - col2.g) <= d) && (Abs(col1.r - col2.r) <= d)
}

RGBfromColor(color) {
	return {r: (0xFF0000 & color) >> 16, g: (0xFF00 & color) >> 8, b: 0xFF & color}
}
```
And then on place of check use:
```ahk
if (ColorRGBCompare(GetPix, red, delta) || ColorRGBCompare(GetPix, dark_red, delta)) {
```

**Comment by Kramar1337** [comment]
Corrected. Check.
