### ISSUE TITLE
Ротация для хавок гг | Havoc MC rotation

### ISSUE THREAD

**Issue by Dramorian** [Kramar1337/WutheringWaves-AHK-flex#3]
Хотелось бы увидеть макрос на ггшку. Не знаю насколько это нужно и осуществимо ли.

https://www.prydwen.gg/wuthering-waves/characters/rover-havoc#:~:text=CALCULATIONS-,ROTATION,-This%20is%20the
https://wutheringlab.com/character/rover-havoc-build/#:~:text=Rover%20Havoc%20Burst%20Rotation
https://youtu.be/UrnsviS6EFw?si=lL41-2qnPlgvxxQh

**Comment by Kramar1337** [comment]
Автоматизация длинных комбинаций плохо себя показывает. не получится. На видосе в зависимости от отряда, эхо и всего прочего разная ротация будет. 
Если будут видосы с абузом анимации, как с Чисей, то такие мне скидывай, я добавлю.
