### ISSUE TITLE
Возможно более эффективный макро на чиксу + Анко-денс

### ISSUE THREAD

**Issue by NekoSamura1** [Kramar1337/WutheringWaves-AHK-flex#4]
Энкор (тащем-то и другие персы умеют неебически спамить N1 через отмену анимации с помощью Ultrasonic Pulse Chip), работает прмерно так:
```
	MouseClick, left
	Sleep, 1
	Send, t ; Тут юзается Ultrasonic Pulse Chip
	Sleep, 80 ; C этой хуйней нужно играться, чем больше - тем стабильнее, чем меньше - тем профитнее по МВ'Су, отличается от используемого перса
```
у чиксы на автоатаке первой сильно больше мноржитель, чем на прицельном выстреле, мб имеет смысл тыкать что-то вроде 
```
	MouseClick, left;                           N1
	Sleep 1;                         вот тут жесть как не уверен по задержке
;здесь можно T прожать, возможно повысит стабильность, но лично не пробовал ибо похуй 
	Send g;                                          Вход в прицел       
	Sleep 1
	MouseClick, left;                            С1
	Sleep 20
	Send g;                                           Выход из прицела
	Sleep 20
```
Сам так и не заставил нормально работать, впрочем скорее потому что на чиксе не играю от слова совсем, а моя любимая ебань с таймингами просто ради ничего - не интересно.

**Comment by NekoSamura1** [comment]
там еще есть прикол в том, что тайминг обычной атаки и атаки в ульте - разный, есть чел у которого работает тупой спам лкм-т без задержек, но я не этот чел

**Comment by Kramar1337** [comment]
затестил я спам Encore через "Ultrasonic Pulse Chip", жижа какая-то получилась.
видосик бы, чтобы наглядно продемонстрировать.

**Comment by NekoSamura1** [comment]
https://youtu.be/1sgKTEbWtRo
```
	MouseClick, left
	Sleep, 1
	Send, {t down} ; Тут юзается (уже нерабочий*) Ultrasonic Pulse Chip
	Sleep, 1
	Send, {t up}
	Sleep, 70 ;
```
Чуть больше инфы: сегодня в дискорде тестили, у челов, что используют  макросы через драйвера или подобную софтину для мышек непосредственно очень стабильно работает:
```
нажать лкм 
1 мс 
отпустить лкм 
1 мс 
нажать т 
1 мс 
отпустить т 
1 мс)
```
у меня через автохоткей так не работает, что служи этому причиной - хз, то ли пинг 130, то ли внезапный фпс<60, то ли AHK принципиально не нравится игре, к сожалению никто не согласился ставить AHK , а я далеко не в МСК

**Comment by Kramar1337** [comment]
https://github.com/Kramar1337/WutheringWaves-AHK-flex/assets/73392036/8af38633-9c9a-4e34-aa9f-57dcbc1ba7c7

хотелось бы чтобы было так

**Comment by Kramar1337** [comment]
макрос с подвохом, нужно качнуть уровень птом делать квест, а по итогу урона мало. Но как абуз механика интересная. Слепил пачку макросов для разных персов. обновляй проверяй.
Если будут еще интересные абузы и желательно с видосом, пиши, я добавлю
