### ISSUE TITLE
Замедление времени, работающее примерно всегда

### ISSUE THREAD

**Issue by NekoSamura1** [Kramar1337/WutheringWaves-AHK-flex#5]
вероятно пофиксят, но пока работает - это просто охуеть. выполняться чкрипт должен 1 раз, ему достаточно
```
Z::
	Send q ;                 это ульта, она должна быть заряжена
	SendInput {vk9} ;   это выбор инструмента (таб)
	Sleep 200
	Return
```
вот микровидосик, чтобы не грузить на ютуб
https://github.com/Kramar1337/WutheringWaves-AHK-flex/assets/107310396/c1134920-9e47-45de-9346-fbce2f7095af

**Comment by Kramar1337** [comment]
ахyеть
